apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "fleet-dispatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fleet-dispatch.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "fleet-dispatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fleet-dispatch.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
