apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: fleet-dispatch-backend
    newName: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/backend
    newTag: a91b380128493b05d5d4a5e58f75d59aed03728c
  - name: fleet-dispatch-frontend
    newName: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/frontend
    newTag: c66371be6ff8ec83b3fc22d3fde032ce7892f61a
replicas:
  - name: frontend
    count: 1
