apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: fleet-dispatch-backend
    newName: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/backend
    newTag: 2375b551574774a1fb7d88965fec915be650e9d4
  - name: fleet-dispatch-frontend
    newName: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/frontend
    newTag: 9cc02774d779347a8024bf3c97c63f9ce552720e
replicas:
  - name: frontend
    count: 1
