backend:
  image:
    repository: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/backend
    tag: 16b7774d553fa248d7ad2ec214a7cef0f30921ae
frontend:
  image:
    repository: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/frontend
    tag: 16b7774d553fa248d7ad2ec214a7cef0f30921ae
  replicas: 1
ingress:
  host: docker-linhdt.site
  tls:
    secretName: docker-linhdt-tls
