backend:
  image:
    repository: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/backend
    tag: 0aa13169b4e7906594ace7333545a579b4cb6fe5
frontend:
  image:
    repository: asia-southeast1-docker.pkg.dev/c2-app-501203/fleet-dispatch-images/frontend
    tag: 0aa13169b4e7906594ace7333545a579b4cb6fe5
  replicas: 1
ingress:
  host: docker-linhdt.site
  tls:
    secretName: docker-linhdt-tls
