apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleet-dispatch

labels:
  - pairs:
      app.kubernetes.io/part-of: fleet-dispatch

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml
  - resource-quota.yaml
